apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deployment
  namespace: podinfo
  labels:
    app: podinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.0.0
        ports:
        - containerPort: 9898
        envFrom:
        - configMapRef:
            name: podinfo-config