apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
  namespace: podinfo
  labels:
    app: podinfo
spec:
  selector:
    app: podinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
  type: ClusterIP