apiVersion: v1
kind: Service
metadata:
  name: edge-nginx-service
  namespace: edge
spec:
  selector:
    app: edge-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
