apiVersion: v1
kind: Service
metadata:
  name: fog-nginx-service
  namespace: fog
spec:
  selector:
    app: fog-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
